// routes
export const FETCH_ROUTES_START = 'FETCH_ROUTES_START';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_ERROR = 'FETCH_ROUTES_ERROR';
export const FETCH_ROUTE_START = 'FETCH_ROUTE_START';
export const FETCH_ROUTE_SUCCESS = 'FETCH_ROUTE_SUCCESS';
export const FETCH_ROUTE_ERROR = 'FETCH_ROUTE_ERROR';
export const FETCH_ADD_ROUTE_START = 'FETCH_ADD_ROUTE_START';
export const FETCH_ADD_ROUTE_SUCCESS = 'FETCH_ADD_ROUTE_SUCCESS';
export const FETCH_ADD_ROUTE_ERROR = 'FETCH_ADD_ROUTE_ERROR';
export const FETCH_DEL_ROUTE_START = 'FETCH_DEL_ROUTE_START';
export const FETCH_DEL_ROUTE_SUCCESS = 'FETCH_DEL_ROUTE_SUCCESS';
export const FETCH_DEL_ROUTE_ERROR = 'FETCH_DEL_ROUTE_ERROR';
export const FETCH_UPD_ROUTE_START = 'FETCH_UPD_ROUTE_START';
export const FETCH_UPD_ROUTE_SUCCESS = 'FETCH_UPD_ROUTE_SUCCESS';
export const FETCH_UPD_ROUTE_ERROR = 'FETCH_UPD_ROUTE_ERROR';
export const SHOW_ROUTE_EDIT_MODAL_ERROR = 'SHOW_ROUTE_EDIT_MODAL_ERROR';
// modal
export const SHOW_EDIT_MODAL_START = 'SHOW_EDIT_MODAL_START';
export const SHOW_EDIT_MODAL_SUCCESS = 'SHOW_EDIT_MODAL_SUCCESS';
export const SHOW_EDIT_MODAL_ERROR = 'SHOW_EDIT_MODAL_ERROR';
export const HIDE_EDIT_MODAL = 'HIDE_EDIT_MODAL';
export const SHOW_DEL_MODAL = 'SHOW_DEL_MODAL';
export const HIDE_DEL_MODAL = 'HIDE_DEL_MODAL';
// containers
export const FETCH_CONTAINERS_START = 'FETCH_CONTAINERS_START';
export const FETCH_CONTAINERS_SUCCESS = 'FETCH_CONTAINERS_SUCCESS';
export const FETCH_CONTAINERS_ERROR = 'FETCH_CONTAINERS_ERROR';
// users
export const FETCH_USERS_START = 'FETCH_USERS_START';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
// posts
export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';
export const FETCH_POST_START = 'FETCH_POST_START';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_ERROR = 'FETCH_POST_ERROR';
// comments
export const FETCH_COMMENTS_BY_POST_ID_START =
	'FETCH_COMMENTS_BY_POST_ID_START';
export const FETCH_COMMENTS_BY_POST_ID_SUCCESS =
	'FETCH_COMMENTS_BY_POST_ID_SUCCESS';
export const FETCH_COMMENTS_BY_POST_ID_ERROR =
	'FETCH_COMMENTS_BY_POST_ID_ERROR';
export const FETCH_ADD_COMMENT_BY_POST_ID_START =
	'FETCH_ADD_COMMENT_BY_POST_ID_START';
export const FETCH_ADD_COMMENT_BY_POST_ID_SUCCESS =
	'FETCH_ADD_COMMENT_BY_POST_ID_SUCCESS';
export const FETCH_ADD_COMMENT_BY_POST_ID_ERROR =
	'FETCH_ADD_COMMENT_BY_POST_ID_ERROR';
// custom containers (custom route)
export const FETCH_CUSTOM_CONTAINER_START = 'FETCH_CUSTOM_CONTAINER_START';
export const FETCH_CUSTOM_CONTAINER_SUCCESS = 'FETCH_CUSTOM_CONTAINER_SUCCESS';
export const FETCH_CUSTOM_CONTAINER_ERROR = 'FETCH_CUSTOM_CONTAINER_ERROR';
// auth
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
// register
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
